version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  test-deploy:
    jobs:
      - test
#      - build-deploy:
#          requires:
#            - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command:
            mkdir test-results
            pytest --cov="." --html=test-results/report.html
      - store_test_results:
          path: test-results
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a sentiment-analysis-analyze web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a sentiment-analysis-analyze web
